### PR TITLE
Develop/infra

### PR DESCRIPTION
**Pull request by kennyhyun**
https://trello.com/c/BErvBOrv/8-devenv-infra

@taewdy Would you mind if we merge PRs with squash in this repo?

image

### CODE REVIEW

**Comment by taewdy** [comment]
Yep, let's do squash merge.

**Review by taewdy — APPROVED** [review]

**Comment by taewdy** [comment]
Can we setup the repo so that the default strategy is `squash` merge and we need at least one approval to merge?

**Review by kennyhyun — COMMENTED** [review]
Updated storage for https://github.com/kennyhyun/nodejs-s3-thumbnail-generator

for duplication

@taewdy Could not find the config for "default strategy" BTW

**Comment by taewdy** [comment]
These are the configs you can set I believe
Squash Merge : Settings -> Options -> Merge button.  Uncheck Other Merges and enable only the squash.
Minium 1 approval : Branches -> Branch protection rules -> click `Add Rule` -> check `Require pull request reviews before merging`

**Comment by taewdy** [comment]
What's been updated in the generator repo?

**Pull request merged**
